server:
  port: 8082
  error:
    include-stacktrace: never

spring:
  application:
    name: empresa-app
  datasource:
    url: jdbc:mysql://localhost:3306/ethos
    username: root
    password: sptech
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    generate-ddl: true # Criação do banco através do JPA
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect