server:
  port: 8081
spring:
  application:
    name: servico-api

  datasource:
    url: jdbc:postgresql://postgres-servico:5432/postgres
    username: admin
    password: senha123

    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://172.23.0.1:8761/eureka/