server:
  port: 8088
spring:
  application:
    name: servico-api

    cloud:
      openfeign:
        client:
          config:
            prestadoraClient:
              connectTimeout: 3000
              readTimeout: 500
              loggerLevel: BASIC

  datasource:
    url: jdbc:postgresql://localhost:5436/postgres
    username: admin
    password: senha123

    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka